include:
- file: container-image/pipeline.gitlab-ci.yml
  project: devops/tools/ci

variables:
  CONTAINER_IMAGE_REGISTRY_PRODUCTION: $CONTAINER_IMAGE_REGISTRY_REGULAR
  CONTAINER_IMAGE_BUILD_ARGS: |-
    CONTAINER_IMAGE_REGISTRY=${ARTIFACTORY_URL}/dkr
